reset_override:
  target:
    entity:
      integration: cover_automation
      domain:
        - sensor
        - binary_sensor
evaluate_now:
  target:
    entity:
      integration: cover_automation
      domain:
        - sensor
        - binary_sensor
